---
title: "Mortality in South African Provinces"
author: "Julia Silge"
date: "2/5/2017"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

## Plot without Shiny

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(southafricastats)

totals <- population_zaf %>% 
    filter(year == 2013) %>% 
    select(province, total)


compare_provinces <- mortality_zaf %>%
    left_join(population_zaf) %>%
    filter(!is.na(total)) %>%
    mutate(mortality = deaths / total * 1e3) %>%
    group_by(province, indicator) %>%
    summarise(mortality = mean(mortality, na.rm = TRUE)) %>%
    ungroup %>%
    left_join(totals) %>%
    spread(indicator, mortality)
    
```


```{r, fig.width=8, fig.height=6, echo=FALSE}
ggplot(compare_provinces, aes(`Cerebrovascular diseases (I60-I69)`,
                              `Diabetes mellitus (E10-E14)`,
                              size = total,
                              label = province)) +
    geom_point(alpha = 0.7, color = "midnightblue") +
    geom_text(aes(size = 3e6), vjust = 2.5) +
    theme_minimal() +
    theme(legend.position="none")
```

## Interactive Shiny version of plot

```{r, echo = FALSE}
selectInput(inputId = "x", 
            label = "X-axis:",
            choices = colnames(compare_provinces)[3:20], 
            selected = "Other forms of heart disease (I30-I52)")

selectInput(inputId = "y", 
            label = "Y-axis:",
            choices = colnames(compare_provinces)[3:20], 
            selected = "Non-natural causes")
```

```{r, echo = FALSE, fig.width=8, fig.height=8}

selected_df <- reactive({
    subset_df <- compare_provinces[, c(1:2, 
                                       which(colnames(compare_provinces) == input$x),
                                       which(colnames(compare_provinces) == input$y))]
    colnames(subset_df) <- c("province", "total", "selected_x", "selected_y")
    subset_df
})

fillCol(height = 800, 
        renderPlot({
            ggplot(selected_df(), aes(x = selected_x,
                                      y = selected_y,
                                      size = total,
                                      label = province)) +
                geom_point(alpha = 0.7, color = "midnightblue") +
                theme_minimal() +
                labs(x = input$x, y = input$y) +
                geom_text(aes(size = 1e7), vjust = 2) +
                theme_minimal(base_size = 14) +
                theme(legend.position="none")
        }, height = 800)
)
```

